// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto.proto

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface protocoleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string fileName = 1;
    boolean hasFileName();
    String getFileName();
    
    // optional string ip = 7;
    boolean hasIp();
    String getIp();
    
    // optional int32 port = 8;
    boolean hasPort();
    int getPort();
    
    // optional string hash = 2;
    boolean hasHash();
    String getHash();
    
    // optional string operation = 3;
    boolean hasOperation();
    String getOperation();
    
    // optional string fileList = 4;
    boolean hasFileList();
    String getFileList();
    
    // optional string response = 5;
    boolean hasResponse();
    String getResponse();
    
    // optional bytes data = 6;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class protocole extends
      com.google.protobuf.GeneratedMessage
      implements protocoleOrBuilder {
    // Use protocole.newBuilder() to construct.
    private protocole(Builder builder) {
      super(builder);
    }
    private protocole(boolean noInit) {}
    
    private static final protocole defaultInstance;
    public static protocole getDefaultInstance() {
      return defaultInstance;
    }
    
    public protocole getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Proto.internal_static_protocole_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Proto.internal_static_protocole_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string fileName = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object fileName_;
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string ip = 7;
    public static final int IP_FIELD_NUMBER = 7;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 port = 8;
    public static final int PORT_FIELD_NUMBER = 8;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPort() {
      return port_;
    }
    
    // optional string hash = 2;
    public static final int HASH_FIELD_NUMBER = 2;
    private java.lang.Object hash_;
    public boolean hasHash() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string operation = 3;
    public static final int OPERATION_FIELD_NUMBER = 3;
    private java.lang.Object operation_;
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          operation_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fileList = 4;
    public static final int FILELIST_FIELD_NUMBER = 4;
    private java.lang.Object fileList_;
    public boolean hasFileList() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getFileList() {
      java.lang.Object ref = fileList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileList_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileListBytes() {
      java.lang.Object ref = fileList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string response = 5;
    public static final int RESPONSE_FIELD_NUMBER = 5;
    private java.lang.Object response_;
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          response_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes data = 6;
    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      fileName_ = "";
      ip_ = "";
      port_ = 0;
      hash_ = "";
      operation_ = "";
      fileList_ = "";
      response_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(2, getHashBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(3, getOperationBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(4, getFileListBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(5, getResponseBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(6, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(7, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(8, port_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHashBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOperationBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFileListBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getResponseBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Proto.protocole parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Proto.protocole parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Proto.protocole parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Proto.protocole parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Proto.protocole parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Proto.protocole parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Proto.protocole parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Proto.protocole parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Proto.protocole parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Proto.protocole parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Proto.protocole prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Proto.protocoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Proto.internal_static_protocole_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Proto.internal_static_protocole_fieldAccessorTable;
      }
      
      // Construct using Proto.protocole.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        hash_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        operation_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        fileList_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        response_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Proto.protocole.getDescriptor();
      }
      
      public Proto.protocole getDefaultInstanceForType() {
        return Proto.protocole.getDefaultInstance();
      }
      
      public Proto.protocole build() {
        Proto.protocole result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Proto.protocole buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Proto.protocole result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Proto.protocole buildPartial() {
        Proto.protocole result = new Proto.protocole(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.fileList_ = fileList_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Proto.protocole) {
          return mergeFrom((Proto.protocole)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Proto.protocole other) {
        if (other == Proto.protocole.getDefaultInstance()) return this;
        if (other.hasFileName()) {
          setFileName(other.getFileName());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasFileList()) {
          setFileList(other.getFileList());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000008;
              hash_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000010;
              operation_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000020;
              fileList_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000040;
              response_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000080;
              data_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000002;
              ip_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000004;
              port_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string fileName = 1;
      private java.lang.Object fileName_ = "";
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      void setFileName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
      }
      
      // optional string ip = 7;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
      }
      
      // optional int32 port = 8;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // optional string hash = 2;
      private java.lang.Object hash_ = "";
      public boolean hasHash() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hash_ = value;
        onChanged();
        return this;
      }
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      void setHash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        hash_ = value;
        onChanged();
      }
      
      // optional string operation = 3;
      private java.lang.Object operation_ = "";
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOperation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        operation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      void setOperation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        operation_ = value;
        onChanged();
      }
      
      // optional string fileList = 4;
      private java.lang.Object fileList_ = "";
      public boolean hasFileList() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getFileList() {
        java.lang.Object ref = fileList_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileList(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        fileList_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileList() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fileList_ = getDefaultInstance().getFileList();
        onChanged();
        return this;
      }
      void setFileList(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        fileList_ = value;
        onChanged();
      }
      
      // optional string response = 5;
      private java.lang.Object response_ = "";
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResponse(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        response_ = value;
        onChanged();
        return this;
      }
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000040);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      void setResponse(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        response_ = value;
        onChanged();
      }
      
      // optional bytes data = 6;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocole)
    }
    
    static {
      defaultInstance = new protocole(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocole)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocole_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocole_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Proto.proto\"\212\001\n\tprotocole\022\020\n\010fileName\030" +
      "\001 \001(\t\022\n\n\002ip\030\007 \001(\t\022\014\n\004port\030\010 \001(\005\022\014\n\004hash\030" +
      "\002 \001(\t\022\021\n\toperation\030\003 \001(\t\022\020\n\010fileList\030\004 \001" +
      "(\t\022\020\n\010response\030\005 \001(\t\022\014\n\004data\030\006 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocole_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocole_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocole_descriptor,
              new java.lang.String[] { "FileName", "Ip", "Port", "Hash", "Operation", "FileList", "Response", "Data", },
              Proto.protocole.class,
              Proto.protocole.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
